portfolio_manager/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("portfolio.urls")),
]

portfolio_manager/portfolio/urls.py
from django.urls import path
from . import views

app_name    = "portfolio"
urlpatterns = [ 
    path("", views.index, name="index"),
]

portfolio_manager/portfolio/models.py
from django.db import models
from django.utils import timezone

#店舗テーブル
class Store(models.Model):

    name    = models.CharField(verbose_name="店舗名",max_length=30)

    #CHECK1: この担当者は管理サイトへログインするユーザーである場合、ユーザーモデルと1対多を組んだほうが良いかも。
    manager = models.CharField(verbose_name="担当者",max_length=10)

    #CHECK2: この契約ステータスは複数のステータスから選ぶ形式の場合、CharFieldのchoicesを使う方が良いかも。
    # https://noauto-nolife.com/post/django-models-choices/ 
    status  = models.IntegerField(verbose_name="契約ステータス")
    


#データテーブル(※店舗のデータテーブルなのでStoreDataとした。)
class StoreData(models.Model):

    store   = models.ForeignKey(Store,verbose_name="店舗",on_delete=models.CASCADE)

    #CHECK3: 記録するものが年月だけであればDateFieldでも良いかも。
    dt      = models.DateTimeField(verbose_name="年月",default=timezone.now)

    #CHECK4: ER図によると売上ID、アクセスID、転換率ID、客単価IDの4つがある。しかし、それらはこのStoreDataのidでよいのでは？


#売上テーブル
class Sale(models.Model):

    dt      = models.DateTimeField(verbose_name="年月",default=timezone.now)

    pc      = models.IntegerField(verbose_name="PC")
    phone   = models.IntegerField(verbose_name="スマホ")
    app     = models.IntegerField(verbose_name="アプリ")


    store_data  = models.ForeignKey(StoreData, verbose_name="データ", on_delete=models.CASCADE)


#売上件数テーブル
class SaleAmount(models.Model):

    dt      = models.DateTimeField(verbose_name="年月",default=timezone.now)

    pc      = models.IntegerField(verbose_name="PC")
    phone   = models.IntegerField(verbose_name="スマホ")
    app     = models.IntegerField(verbose_name="アプリ")

    store_data  = models.ForeignKey(StoreData, verbose_name="データ", on_delete=models.CASCADE)

#アクセス人数テーブル
class Access(models.Model):

    dt      = models.DateTimeField(verbose_name="年月",default=timezone.now)

    pc      = models.IntegerField(verbose_name="PC")
    phone   = models.IntegerField(verbose_name="スマホ")
    app     = models.IntegerField(verbose_name="アプリ")

    store_data  = models.ForeignKey(StoreData, verbose_name="データ", on_delete=models.CASCADE)

#転換率テーブル
class ConversionRate(models.Model):

    dt      = models.DateTimeField(verbose_name="年月",default=timezone.now)

    pc      = models.FloatField(verbose_name="PC")
    phone   = models.FloatField(verbose_name="スマホ")
    app     = models.FloatField(verbose_name="アプリ")

    store_data  = models.ForeignKey(StoreData, verbose_name="データ", on_delete=models.CASCADE)

portfolio_manager/portfolio/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "portfolio/index.html")

index   = IndexView.as_view()

portfolio_manager/templates/common/l_sidebar.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block page_title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'common/css/l_sidebar.css' %}">

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    <header>
        <input id="l_sidebar" class="l_sidebar_button" type="checkbox">
        <div class="left_header">
            <label class="l_sidebar_label" for="l_sidebar">
                <i class="fas fa-bars"></i>
                <i class="fas fa-times"></i>
            </label>
            <a class="header_link" href="{% block header_link %}{% endblock %}"><h1>{% block header_title %}{% endblock %}</h1></a>
            <div class="header_right_content">
            {% block header_right_content %}
            {% endblock %}
            </div>
        </div>
        <div class="l_sidebar_menu">
            {% block sidebar_content %}{% endblock %}
        </div>
        <label class="l_sidebar_closer" for="l_sidebar"></label>
    </header>

    <main>
    {% block main %}
    {% endblock %}
    </main>

</body>
</html>

portfolio_manager/templates/portfolio/index.html
{% extends "common/l_sidebar.html" %}



<!--追加でCSSを読み込ませる。今回はBootstrap-->
{% block extra_head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}

{% block page_title %}簡易掲示板{% endblock %}

{% block header_link %}{% url 'portfolio:index' %}{% endblock %}
{% block header_title %}簡易掲示板{% endblock %}

<!--↓これはヘッダーの右側に何かを表示させたい時に使う。例えばログインのボタンとか-->
{% block header_right_content %}{% endblock %}

<!--↓これは左サイドバーの中身に何かを表示させたい時に使う。例えばサイト内のリンクとか-->
{% block sidebar_content %}{% endblock %}

{% block main %}
<main class="container">
    <form method="POST">
        {% csrf_token %}
        <textarea class="form-control" name="comment"></textarea>
        <input type="submit" value="送信">
    </form>

</main>
{% endblock %}